#!/usr/bin/env python3
"""Code Improvement Worker — lint checks, quality analysis, GitHub Issue reporting.

Runs ruff on the source tree, groups issues by file, and opens a GitHub Issue
with a structured report.  Skips if a recent open issue already exists.
Mentions @Copilot so GitHub Copilot can auto-suggest fixes for free.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
REPORT_PATH = ROOT / "lint-report.json"
ISSUE_TITLE_PREFIX = "[Code Quality]"


# ── Helpers ──────────────────────────────────────────────────────────────────


def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, **kwargs)


def ensure_labels() -> None:
    for name, color, desc in [
        ("automated", "0075ca", "Auto-generated by scheduled workers"),
        ("code-quality", "e4e669", "Code quality / lint improvements"),
        ("agent-gap", "d93f0b", "Missing agent domain coverage"),
        ("pattern", "1d76db", "Discovered code or agent pattern"),
    ]:
        run(["gh", "label", "create", name,
             "--color", color, "--description", desc, "--force"])


def open_issue_exists(prefix: str) -> bool:
    r = run(["gh", "issue", "list", "--state", "open",
             "--json", "title", "--limit", "30"])
    if r.returncode != 0:
        return False
    try:
        return any(i["title"].startswith(prefix) for i in json.loads(r.stdout))
    except (json.JSONDecodeError, KeyError):
        return False


def create_issue(title: str, body: str, labels: list[str]) -> None:
    args = ["gh", "issue", "create", "--title", title, "--body", body]
    for lbl in labels:
        args += ["--label", lbl]
    result = run(args)
    if result.returncode == 0:
        print(f"Issue created: {title}")
    else:
        print(f"gh issue create failed: {result.stderr}", file=sys.stderr)


# ── Linting ───────────────────────────────────────────────────────────────────


def run_ruff_json() -> list[dict]:
    r = run(["ruff", "check", str(ROOT / "future_agents"),
             "--output-format", "json", "--quiet"])
    if r.stdout.strip():
        try:
            return json.loads(r.stdout)
        except json.JSONDecodeError:
            pass
    return []


def run_ruff_stats() -> str:
    r = run(["ruff", "check", str(ROOT / "future_agents"), "--statistics"])
    return r.stdout.strip() or "No issues found."


# ── Report building ───────────────────────────────────────────────────────────


def build_report(issues: list[dict], stats: str) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    by_file: dict[str, list[dict]] = {}
    for issue in issues:
        by_file.setdefault(issue.get("filename", "unknown"), []).append(issue)

    lines = [
        f"## Code Quality Report — {today}",
        "",
        f"**{len(issues)} lint issues** found across **{len(by_file)} files**.",
        "",
        "### Statistics",
        "```",
        stats,
        "```",
        "",
        "### Issues by File",
        "",
    ]

    for filepath, file_issues in sorted(by_file.items(), key=lambda x: -len(x[1]))[:10]:
        try:
            rel = Path(filepath).relative_to(ROOT)
        except ValueError:
            rel = Path(filepath)
        lines.append(f"#### `{rel}` ({len(file_issues)} issues)")
        for fi in file_issues[:5]:
            row = fi.get("location", {}).get("row", "?")
            code = fi.get("code", "?")
            msg = fi.get("message", "")
            lines.append(f"- Line {row}: `{code}` — {msg}")
        if len(file_issues) > 5:
            lines.append(f"- *… and {len(file_issues) - 5} more*")
        lines.append("")

    lines += [
        "### Quick Fix",
        "",
        "```bash",
        "ruff check --fix future_agents/",
        "ruff format future_agents/",
        "```",
        "",
        "> 🤖 Auto-generated by **Code Improvement Worker** (GitHub Actions).",
        "> @Copilot please review the issues above and suggest the most impactful fixes.",
    ]
    return "\n".join(lines)


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    ensure_labels()

    issues = run_ruff_json()
    stats = run_ruff_stats()

    # Save artifact for the upload step
    REPORT_PATH.write_text(json.dumps(issues, indent=2))

    print(f"Lint issues found: {len(issues)}")

    if not issues:
        print("✓ Code quality is clean — no issues to report.")
        return

    if open_issue_exists(ISSUE_TITLE_PREFIX):
        print("Open code-quality issue already exists — skipping.")
        return

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = f"{ISSUE_TITLE_PREFIX} {len(issues)} lint issues ({today})"
    body = build_report(issues, stats)

    create_issue(title, body, labels=["automated", "code-quality"])


if __name__ == "__main__":
    main()
