#!/usr/bin/env python3
"""Knowledge Synthesis Worker script — uses Claude to synthesise insights from JSON knowledge files.

Reads knowledge entries stored as JSON in knowledge/, synthesises themes and
recommendations via Claude, and creates a GitHub Issue with the synthesis.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
KNOWLEDGE_DIR = ROOT / "knowledge"
ISSUE_TITLE_PREFIX = "[Knowledge Synthesis]"

try:
    import anthropic

    _ANTHROPIC_AVAILABLE = True
except ImportError:
    _ANTHROPIC_AVAILABLE = False


# ── Helpers ───────────────────────────────────────────────────────────────────


def run(cmd: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True)


def open_issue_exists(prefix: str) -> bool:
    r = run(["gh", "issue", "list", "--state", "open", "--json", "title", "--limit", "30"])
    if r.returncode != 0:
        return False
    try:
        return any(i["title"].startswith(prefix) for i in json.loads(r.stdout))
    except (json.JSONDecodeError, KeyError):
        return False


def load_knowledge_entries() -> list[dict]:
    if not KNOWLEDGE_DIR.exists():
        return []
    entries = []
    for f in sorted(KNOWLEDGE_DIR.glob("*.json")):
        try:
            entries.append(json.loads(f.read_text()))
        except (json.JSONDecodeError, OSError):
            pass
    return entries


# ── Claude synthesis ──────────────────────────────────────────────────────────


def synthesise(entries: list[dict]) -> str:
    if not _ANTHROPIC_AVAILABLE:
        return (
            "anthropic package not installed. "
            "Add ANTHROPIC_API_KEY secret and install with: pip install anthropic"
        )

    entries_text = "\n\n".join(
        f"[{e.get('domain', 'unknown')}] {e.get('title', 'Untitled')}\n{e.get('content', '')}"
        for e in entries[:20]
    )
    prompt = (
        f"Below are {len(entries[:20])} knowledge entries from an AI agent system.\n\n"
        f"{entries_text}\n\n"
        f"Please:\n"
        f"1. Identify the 3 most important themes or insights across these entries.\n"
        f"2. Note any contradictions or tensions between entries.\n"
        f"3. Provide 2-3 concrete, actionable recommendations for the system.\n"
        f"Format your response with clear headings."
    )

    client = anthropic.Anthropic()
    response = client.messages.create(
        model="claude-opus-4-7",
        max_tokens=2048,
        thinking={"type": "adaptive"},
        messages=[{"role": "user", "content": prompt}],
    )
    return "\n".join(b.text for b in response.content if hasattr(b, "text"))


# ── Issue creation ────────────────────────────────────────────────────────────


def create_issue(entries: list[dict], synthesis: str) -> None:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = f"{ISSUE_TITLE_PREFIX} Insights from {len(entries)} entries — {today}"

    body = "\n".join(
        [
            f"## Knowledge Synthesis Report — {today}",
            "",
            f"Synthesised **{len(entries)} knowledge entries** using Claude.",
            "",
            "### Synthesis",
            "",
            synthesis,
            "",
            "---",
            "> 🤖 Auto-generated by **Knowledge Synthesis Worker** (GitHub Actions).",
            "> @Copilot please review the synthesis and suggest follow-up actions.",
        ]
    )

    r = run(
        [
            "gh",
            "issue",
            "create",
            "--title",
            title,
            "--body",
            body,
            "--label",
            "automated,knowledge-synthesis",
        ]
    )
    if r.returncode == 0:
        print(f"Issue created: {title}")
    else:
        print(f"gh issue create failed: {r.stderr}", file=sys.stderr)


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    print("Running knowledge synthesis...")
    entries = load_knowledge_entries()
    print(f"  Knowledge entries found: {len(entries)}")

    if len(entries) < 3:
        print("  Not enough entries to synthesise — skipping.")
        return

    if open_issue_exists(ISSUE_TITLE_PREFIX):
        print("Recent synthesis issue already exists — skipping.")
        return

    print("  Synthesising with Claude...")
    synthesis = synthesise(entries)
    create_issue(entries, synthesis)


if __name__ == "__main__":
    main()
