"""Each section of the project record, rendered from run state.

Two rules everything here follows. **Nothing is invented** — every line traces to
an artifact the run produced, so a document cannot be more confident than the
delivery was. And **a section with nothing to say says so**: an empty QA file and
a missing one mean very different things to whoever is reading at 9am on a
Monday trying to work out whether this shipped.
"""

from __future__ import annotations

import re
from typing import Optional

from future_agents.sdd.models import (
    MetricSet,
    RunState,
    SemanticModel,
    WorkBreakdown,
)
from future_agents.sdd.project_docs.mermaid import (
    method_diagram,
    structure_diagram,
    traceability_diagram,
)

_EMPTY = "_Nothing recorded — this run did not reach that stage._"


def slug_for(text: str, limit: int = 48) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", (text or "").lower())[:limit].strip("-")
    return slug or "delivery"


# ── README ────────────────────────────────────────────────────────────────────


def readme_md(
    state: RunState,
    semantics: Optional[SemanticModel],
    breakdown: Optional[WorkBreakdown],
    metrics: Optional[MetricSet],
    root: str,
) -> str:
    spec = state.spec
    qa = state.qa
    title = spec.title if spec else state.objective.statement
    lines = [
        f"# {title}",
        "",
        state.objective.statement,
        "",
        "| | |",
        "|---|---|",
        f"| **Status** | {state.stage.value} |",
        f"| **Requested by** | {state.objective.submitted_by or 'unknown'} |",
        f"| **Source** | {state.objective.source.value}"
        + (f" ({state.objective.external.key})" if state.objective.external else "")
        + " |",
        f"| **Run** | `{state.id}` |",
        f"| **QA** | {qa.verdict.value.upper() if qa else '—'}"
        + (f" · MUST coverage {qa.coverage:.0%}" if qa else "")
        + " |",
        f"| **Domain** | {semantics.domain if semantics else '—'} |",
        f"| **Work items** | {len(breakdown.items) if breakdown else 0} |",
        f"| **Metrics** | {len(metrics.specs) if metrics else 0} |",
        "",
        "## Contents",
        "",
        "| Document | What it answers |",
        "|---|---|",
        "| [01-objective](01-objective.md) | What was asked, by whom, and what was clarified |",
        "| [02-semantics](02-semantics.md) | What the words mean here, and how the ask was read |",
        "| [03-architecture](03-architecture.md) | What gets built and where it goes |",
        "| [04-work-breakdown](04-work-breakdown.md) | Every tracked item and its issue |",
        "| [05-implementation](05-implementation.md) | What actually ran, with evidence |",
        "| [06-qa](06-qa.md) | Whether it works, and how we know |",
        "| [07-observability](07-observability.md) | How we would know it broke |",
        "| [08-metrics](08-metrics.md) | What we measure, and the question each answers |",
        "| [09-decisions](09-decisions.md) | What was decided, and why |",
        "| [10-changelog](10-changelog.md) | The run, event by event |",
        "",
        "## Method",
        "",
        "The steps this delivery went through:",
        "",
        method_diagram(
            [event.stage.value for event in _stage_sequence(state)] or ["intake"],
            gates=["constitution gates", "QA evidence rule", "observability gate"],
        ),
        "",
        f"_Generated by spec-driven delivery into `{root}`. Regenerate rather than edit._",
    ]
    return "\n".join(lines) + "\n"


# ── 01 Objective ──────────────────────────────────────────────────────────────


def objective_md(state: RunState) -> str:
    objective = state.objective
    clarification = state.clarification
    spec = state.spec
    lines = [
        "# Objective",
        "",
        "## The ask, as it arrived",
        "",
        f"> {objective.statement}",
        "",
        "| | |",
        "|---|---|",
        f"| **Requested by** | {objective.submitted_by or 'unknown'} |",
        f"| **Channel** | {objective.source.value} |",
    ]
    if objective.external:
        lines.append(f"| **Ticket** | {objective.external.key or '—'} |")
        if objective.external.url:
            lines.append(f"| **Link** | {objective.external.url} |")
        if objective.external.labels:
            lines.append(f"| **Labels** | {', '.join(objective.external.labels)} |")
    lines.append(f"| **Received** | {objective.created_at.isoformat()} |")
    untrusted = "yes — sanitised at intake" if objective.untrusted else "no"
    lines.append(f"| **Untrusted text** | {untrusted} |")
    lines.append("")

    if objective.context:
        lines += ["## Context given", "", objective.context, ""]
    if objective.constraints:
        lines += ["## Constraints", ""] + [f"- {c}" for c in objective.constraints] + [""]

    lines += ["## Clarification", ""]
    if clarification is None:
        lines.append(_EMPTY)
    else:
        lines += [
            f"Outcome: **{clarification.outcome.value}** at confidence "
            f"{clarification.confidence} — {clarification.rationale}",
            "",
        ]
        answered = [q for q in clarification.questions if q.answered]
        open_questions = [q for q in clarification.questions if not q.answered]
        if answered:
            lines += ["### Answered", ""]
            for question in answered:
                by = question.answered_by or "human"
                lines.append(f"- **{question.text}**  \n  {question.answer} _({by})_")
            lines.append("")
        if open_questions:
            lines += ["### Still open", ""]
            lines += [f"- {'**blocking** ' if q.blocking else ''}{q.text}" for q in open_questions]
            lines.append("")
        if clarification.assumptions:
            lines += ["### Assumed, not confirmed", ""]
            for assumption in clarification.assumptions:
                lines.append(
                    f"- {assumption.statement} — _{assumption.basis}_ "
                    f"(risk: {assumption.risk}, source: {assumption.source})"
                )
            lines.append("")
        if clarification.meeting:
            meeting = clarification.meeting
            lines += [
                "### Meeting",
                "",
                f"- **{meeting.title}** ({meeting.status.value}) — {meeting.reason}",
                *[f"  - {item}" for item in meeting.agenda],
                "",
            ]

    if spec is not None:
        lines += [
            "## Requirements",
            "",
            "| Id | Priority | Requirement | Criteria |",
            "|---|---|---|---|",
        ]
        for requirement in spec.requirements:
            lines.append(
                f"| `{requirement.id}` | {requirement.priority.value} | {requirement.statement} | "
                f"{len(requirement.acceptance_criteria)} |"
            )
        lines.append("")
        if spec.out_of_scope:
            lines += ["**Out of scope:** " + "; ".join(spec.out_of_scope), ""]
        if spec.success_metrics:
            lines += ["**Success metrics named in the ask:**", ""]
            lines += [f"- {metric}" for metric in spec.success_metrics]
            lines.append("")
    return "\n".join(lines) + "\n"


# ── 02 Semantics ──────────────────────────────────────────────────────────────


def semantics_md(state: RunState, semantics: Optional[SemanticModel]) -> str:
    lines = ["# Semantics — what the words mean here", ""]
    if semantics is None:
        return "\n".join(lines + [_EMPTY]) + "\n"

    lines += [
        f"Domain: **{semantics.domain}**. "
        f"{len(semantics.concepts)} term(s) resolved into "
        f"{len(semantics.capabilities)} capability(ies).",
        "",
        "## How the ask was read",
        "",
    ]
    lines += [f"{index}. {step}" for index, step in enumerate(semantics.trace, start=1)]
    lines += ["", "## Capabilities", ""]
    if semantics.capabilities:
        lines += ["| Id | Capability | Requirement | So that |", "|---|---|---|---|"]
        for capability in semantics.capabilities:
            lines.append(
                f"| `{capability.id}` | {capability.statement} | "
                f"{', '.join(capability.requirement_ids)} | {capability.outcome or '—'} |"
            )
    else:
        lines.append("_No capability could be named — the ask has no action and no object yet._")
    lines.append("")

    if semantics.ambiguities:
        lines += [
            "## Still ambiguous",
            "",
            "Recorded rather than guessed. Each of these is a question worth asking:",
            "",
        ]
        lines += [f"- {item}" for item in semantics.ambiguities]
        lines.append("")

    grounded = [c for c in semantics.concepts if c.definition]
    if grounded:
        lines += ["## Glossary", "", "| Term | Kind | Meaning | Confidence |", "|---|---|---|---|"]
        for concept in grounded:
            lines.append(
                f"| `{concept.canonical}` | {concept.kind.value} | {concept.definition} | "
                f"{concept.confidence:.2f} |"
            )
        lines.append("")

    if semantics.relations:
        lines += ["## Relations", ""] + [f"- {r}" for r in semantics.relations] + [""]
    return "\n".join(lines) + "\n"


# ── 03 Architecture ───────────────────────────────────────────────────────────


def architecture_md(state: RunState, semantics: Optional[SemanticModel]) -> str:
    plan = state.plan
    spec = state.spec
    lines = ["# Architecture", ""]
    if plan is None or spec is None:
        return "\n".join(lines + [_EMPTY]) + "\n"

    runtime = plan.runtime_stack or "unspecified"
    lines += [plan.architecture or "_No architecture summary._", "", f"Runtime: **{runtime}**", ""]
    lines += ["## Structure", "", structure_diagram(plan, semantics, plan.observability), ""]
    lines += [
        "## Traceability",
        "",
        traceability_diagram(spec, plan, semantics, plan.observability),
        "",
    ]

    lines += [
        "## Components",
        "",
        "| Component | Responsibility | Requirements | Goes in |",
        "|---|---|---|---|",
    ]
    for component in plan.components:
        lines.append(
            f"| {component.name} | {component.responsibility} | "
            f"{', '.join(component.requirement_ids) or '—'} | "
            f"`{component.target_path or 'undecided'}` |"
        )
    lines.append("")

    if plan.placements:
        lines += ["## Placement decisions", ""]
        for placement in plan.placements:
            lines += [
                f"### {placement.requirement_id} → `{placement.target_path}`",
                "",
                f"- **Approach:** {placement.approach} — {placement.rationale}",
                f"- **Tests:** `{placement.test_path or 'not decided'}`",
            ]
            if placement.conventions:
                lines.append("- **Rules that decided it:** " + "; ".join(placement.conventions))
            if placement.alternatives:
                lines.append("- **Alternatives considered:**")
                lines += [
                    f"  - `{alt.path}` ({alt.approach}) — {alt.tradeoff}"
                    for alt in placement.alternatives
                ]
            if placement.forbidden:
                lines.append(
                    "- **Must not go in:** "
                    + "; ".join(f"`{z.path}` ({z.reason})" for z in placement.forbidden)
                )
            lines.append("")

    if plan.risks:
        lines += ["## Risks", "", "| Severity | Risk | Mitigation | Source |", "|---|---|---|---|"]
        for risk in plan.risks:
            lines.append(
                f"| {risk.severity} | {risk.description} | {risk.mitigation or '—'} | "
                f"{risk.source or '—'} |"
            )
        lines.append("")

    if plan.historical_warnings:
        lines += ["## What memory warned about", ""]
        lines += [f"- {warning}" for warning in plan.historical_warnings]
        lines.append("")
    return "\n".join(lines) + "\n"


# ── 04 Work breakdown ─────────────────────────────────────────────────────────


def work_breakdown_md(
    state: RunState,
    breakdown: Optional[WorkBreakdown],
    issue_refs: dict[str, str],
) -> str:
    lines = ["# Work breakdown", ""]
    if breakdown is None or not breakdown.items:
        return "\n".join(lines + [_EMPTY]) + "\n"

    spec_ids = [r.id for r in state.spec.requirements] if state.spec else []
    lines += [
        f"{len(breakdown.items)} tracked item(s). "
        f"Requirement coverage: **{breakdown.coverage(spec_ids):.0%}**.",
        "",
        "## Tree",
        "",
        "```",
        *breakdown.outline(),
        "```",
        "",
        "## Items",
        "",
        "| Item | Kind | Title | Requirements | Issue | Status |",
        "|---|---|---|---|---|---|",
    ]
    for item in breakdown.items:
        ref = issue_refs.get(item.id) or item.external_ref or "—"
        lines.append(
            f"| `{item.id}` | {item.kind.value} | {item.title} | "
            f"{', '.join(item.requirement_ids) or '—'} | {ref} | {item.status.value} |"
        )
    lines.append("")

    lines += ["## Definition of done, per item", ""]
    for item in breakdown.items:
        if not item.definition_of_done:
            continue
        lines.append(f"**{item.id} — {item.title}**")
        lines += [f"- [ ] {entry}" for entry in item.definition_of_done]
        lines.append("")
    return "\n".join(lines) + "\n"


# ── 05 Implementation ─────────────────────────────────────────────────────────


def implementation_md(state: RunState) -> str:
    lines = ["# Implementation", ""]
    graph = state.tasks
    if graph is None:
        return "\n".join(lines + [_EMPTY]) + "\n"

    by_task = {result.task_id: result for result in state.work_results}
    lines += [
        f"{len(graph.tasks)} task(s) in the graph, "
        f"{sum(1 for r in state.work_results if r.status.value == 'done')} completed.",
        "",
        "| Task | Kind | Title | Status | Agent | Evidence |",
        "|---|---|---|---|---|---|",
    ]
    for task in graph.tasks:
        result = by_task.get(task.id)
        evidence = "—"
        if result and result.evidence:
            passing = [e for e in result.evidence if e.passed and not e.simulated]
            evidence = (
                f"{len(passing)} passing"
                if passing
                else ("simulated" if result.simulated else "none passing")
            )
        lines.append(
            f"| `{task.id}` | {task.kind.value} | {task.title} | "
            f"{result.status.value if result else 'not run'} | "
            f"{result.agent_id if result and result.agent_id else '—'} | {evidence} |"
        )
    lines.append("")

    changed = sorted({f for r in state.work_results for f in r.changed_files})
    if changed:
        lines += ["## Files changed", ""] + [f"- `{path}`" for path in changed] + [""]

    commands = [e for r in state.work_results for e in r.evidence if e.command and not e.simulated]
    if commands:
        lines += [
            "## Commands that actually ran",
            "",
            "| Command | Exit | Digest |",
            "|---|---|---|",
        ]
        for evidence in commands[:20]:
            lines.append(
                f"| `{evidence.command}` | {evidence.exit_code} | `{evidence.output_digest}` |"
            )
        lines.append("")

    if state.assignments:
        lines += ["## Who did what", "", "| Task | Agent | Skill | Why |", "|---|---|---|---|"]
        for assignment in state.assignments:
            lines.append(
                f"| `{assignment.task_id}` | {assignment.agent_id} | {assignment.skill_id} | "
                f"{assignment.rationale} |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


# ── 06 QA ─────────────────────────────────────────────────────────────────────


def qa_md(state: RunState) -> str:
    lines = ["# QA results", ""]
    qa = state.qa
    if qa is None:
        return "\n".join(lines + [_EMPTY]) + "\n"

    lines += [
        f"Verdict: **{qa.verdict.value.upper()}**"
        + (" _(simulated — nothing executed)_" if qa.simulated else ""),
        "",
        f"- MUST criteria coverage: **{qa.coverage:.0%}**",
        f"- Instrumentation executed: **{qa.observability_coverage:.0%}**",
        f"- Evidence required: {qa.evidence_required}",
        f"- Environment: {qa.environment}" + (" (cleaned)" if qa.environment_cleaned else ""),
        "",
        "## Behaviour checks",
        "",
        "| Criterion | Requirement | Verified | Covered by | Then |",
        "|---|---|---|---|---|",
    ]
    for check in qa.checks:
        lines.append(
            f"| `{check.criterion_id}` | `{check.requirement_id}` | "
            f"{'yes' if check.verified else 'no'} | "
            f"{', '.join(check.covered_by) or '—'} | {check.then} |"
        )
    lines.append("")

    if qa.findings:
        lines += ["## Findings", "", "| Severity | Finding | Evidence |", "|---|---|---|"]
        for finding in qa.findings:
            lines.append(f"| {finding.severity} | {finding.summary} | {finding.evidence or '—'} |")
        lines.append("")
    else:
        lines += ["## Findings", "", "None.", ""]

    if qa.out_of_scope_ignored:
        lines += [
            "## Fenced as out of scope",
            "",
            ", ".join(f"`{c}`" for c in qa.out_of_scope_ignored),
            "",
        ]

    delivery = state.delivery
    if delivery is not None:
        lines += [
            "## Delivery",
            "",
            f"- Accepted: **{'yes' if delivery.accepted else 'no'}**",
            f"- Coverage: {delivery.coverage:.0%}",
            f"- Runbook: `{delivery.runbook_path or 'none'}`",
        ]
        if delivery.slo_summary:
            lines += ["- Objectives:"] + [f"  - {line}" for line in delivery.slo_summary]
        if delivery.unconfirmed_assumptions:
            lines += ["- Still assumed:"] + [
                f"  - {a.statement}" for a in delivery.unconfirmed_assumptions
            ]
        lines.append("")
    return "\n".join(lines) + "\n"


# ── 07 Observability ──────────────────────────────────────────────────────────


def observability_md(state: RunState) -> str:
    lines = ["# Observability", ""]
    plan = state.plan.observability if state.plan else None
    if plan is None:
        return "\n".join(lines + [_EMPTY]) + "\n"

    lines += [
        f"Telemetry: {plan.telemetry_stack}",
        "",
        f"Runbook: `{plan.runbook_path}`",
        "",
        "## Objectives",
        "",
        "| Id | Kind | Objective | Requirement | Alerts |",
        "|---|---|---|---|---|",
    ]
    for slo in plan.slos:
        alerts = ", ".join(f"{a.severity}" for a in plan.alerts_for(slo.id)) or "—"
        lines.append(
            f"| `{slo.id}` | {slo.kind} | {slo.render()} | `{slo.requirement_id}` | {alerts} |"
        )
    lines.append("")

    lines += [
        "## Signals",
        "",
        "| Id | Signal | Instrument | Emitted from | Read with |",
        "|---|---|---|---|---|",
    ]
    for signal in plan.signals:
        lines.append(
            f"| `{signal.id}` | `{signal.name}` | {signal.instrument} | "
            f"`{signal.emitted_from or '—'}` | `{signal.query or 'trace search'}` |"
        )
    lines.append("")

    if plan.alerts:
        lines += [
            "## Alerts",
            "",
            "| Id | Severity | Condition | Channel | Runbook |",
            "|---|---|---|---|---|",
        ]
        for alert in plan.alerts:
            lines.append(
                f"| `{alert.id}` | {alert.severity} | {alert.condition} | {alert.channel} | "
                f"`{alert.runbook}` |"
            )
        lines.append("")

    if plan.health_checks:
        lines += ["## Health", ""] + [f"- {check}" for check in plan.health_checks] + [""]
    if plan.redactions:
        lines += ["## Never log", "", ", ".join(f"`{f}`" for f in plan.redactions), ""]
    if plan.gaps:
        lines += ["## Blind spots", ""] + [f"- {gap}" for gap in plan.gaps] + [""]
    return "\n".join(lines) + "\n"


# ── 08 Metrics ────────────────────────────────────────────────────────────────


def metrics_md(
    state: RunState,
    metrics: Optional[MetricSet],
    breakdown: Optional[WorkBreakdown],
) -> str:
    lines = ["# Metrics", ""]
    if metrics is None or not metrics.specs:
        return "\n".join(lines + [_EMPTY]) + "\n"

    unbound = [m for m in metrics.specs if m.source == "unbound"]
    lines += [
        f"{len(metrics.specs)} metric(s) across "
        f"{len({m.kind for m in metrics.specs})} families. "
        f"{len(unbound)} still need a data source.",
        "",
    ]
    for kind in sorted({m.kind for m in metrics.specs}, key=lambda k: k.value):
        lines += [
            f"## {kind.value.title()}",
            "",
            "| Id | Metric | Question | Item | Value | Target | Source |",
            "|---|---|---|---|---|---|---|",
        ]
        for metric in metrics.of_kind(kind):
            item = breakdown.by_id(metric.work_item_id) if breakdown else None
            value = "—" if metric.value is None else f"{metric.value:g}{metric.unit}"
            target = "—" if metric.target is None else f"{metric.target:g}{metric.unit}"
            lines.append(
                f"| `{metric.id}` | {metric.name} | {metric.question} | "
                f"`{metric.work_item_id}`{f' {item.title[:28]}' if item else ''} | "
                f"{value} | {target} | {metric.source or '—'} |"
            )
        lines.append("")

    if unbound:
        lines += [
            "## Not yet measurable",
            "",
            "These name an outcome the ask cared about but have no data source. "
            "Binding them is a human decision, not a guess this system should make:",
            "",
        ]
        lines += [f"- `{m.id}` **{m.name}** — {m.question}" for m in unbound]
        lines.append("")

    missed = metrics.unmet()
    if missed:
        lines += ["## Off target", ""] + [f"- {m.render()}" for m in missed] + [""]
    return "\n".join(lines) + "\n"


# ── 09 Decisions ──────────────────────────────────────────────────────────────


def decisions_md(state: RunState, semantics: Optional[SemanticModel]) -> str:
    """Decision records, drawn from what the run actually chose."""
    lines = ["# Decisions", "", "What was decided during this delivery, and on what basis.", ""]
    number = 0
    plan = state.plan

    if plan is not None:
        for placement in plan.placements:
            number += 1
            alternatives = (
                "; ".join(f"`{a.path}` — {a.tradeoff}" for a in placement.alternatives) or "none"
            )
            lines += [
                f"## ADR-{number:03d} — where {placement.requirement_id} lives",
                "",
                f"- **Decision:** `{placement.target_path}` ({placement.approach})",
                f"- **Because:** {placement.rationale or 'repository convention'}",
                f"- **Rejected:** {alternatives}",
                f"- **Confidence:** {placement.confidence:.2f}",
                "",
            ]

    if semantics is not None:
        for concept in semantics.concepts:
            if not concept.ambiguous:
                continue
            number += 1
            lines += [
                f"## ADR-{number:03d} — the meaning of '{concept.canonical}' is still open",
                "",
                f"- **Readings:** {' | '.join(concept.readings)}",
                f"- **Used by:** {', '.join(concept.requirement_ids)}",
                "- **Decision:** deferred to a human; the pipeline did not pick one.",
                "",
            ]

    if state.clarification is not None:
        for assumption in state.clarification.assumptions:
            number += 1
            lines += [
                f"## ADR-{number:03d} — assumed: {assumption.statement}",
                "",
                f"- **Basis:** {assumption.basis}",
                f"- **Risk:** {assumption.risk}",
                f"- **Source:** {assumption.source}",
                f"- **Confirmed:** {'yes' if assumption.confirmed else 'no'}",
                "",
            ]

    if number == 0:
        lines.append(_EMPTY)
    return "\n".join(lines) + "\n"


# ── 10 Changelog ──────────────────────────────────────────────────────────────


def changelog_md(state: RunState) -> str:
    lines = [
        "# Changelog",
        "",
        f"Run `{state.id}` — schema v{state.schema_version}, last updated "
        f"{state.updated_at.isoformat()}.",
        "",
        "| When | Stage | What happened |",
        "|---|---|---|",
    ]
    for event in state.events:
        lines.append(
            f"| {event.at.isoformat(timespec='seconds')} | {event.stage.value} | {event.message} |"
        )
    if not state.events:
        lines.append("| — | — | _no events_ |")
    lines.append("")
    if state.case_id:
        lines += [f"Harvested into memory case `{state.case_id}`.", ""]
    return "\n".join(lines) + "\n"


def _stage_sequence(state: RunState) -> list:
    """Stages in the order they first happened, without repeats."""
    seen: set[str] = set()
    ordered = []
    for event in state.events:
        if event.stage.value in seen:
            continue
        seen.add(event.stage.value)
        ordered.append(event)
    return ordered
