"""Spec-Driven Delivery — objective in, verified delivery out.

from future_agents.sdd import DeliveryPipeline, Objective, SpecKitConfig

cfg = SpecKitConfig.load()
state = DeliveryPipeline(cfg).start(Objective(statement="…"))
if state.awaiting_human:
    state = pipeline.answer(state, {q.id: "…" for q in state.pending_questions()})
"""

from future_agents.sdd.clarify import IntentClarifier
from future_agents.sdd.config import ConfigError, SpecKitConfig
from future_agents.sdd.constitution import Constitution, PatchDecision, Severity, Violation
from future_agents.sdd.execution import (
    BudgetExceeded,
    BudgetGuard,
    CircuitBreaker,
    CompositeBackend,
    DispatchBackend,
    LoopDetector,
    SandboxViolation,
    ToolchainBackend,
    WorkspacePolicy,
)
from future_agents.sdd.intake import (
    SanitizedText,
    detect_adapter,
    objective_from_payload,
    sanitize,
)
from future_agents.sdd.knowledge import (
    Conventions,
    PlacementAdvisor,
    PlacementRule,
    Prohibition,
    RepoIndex,
    RepoKnowledge,
)
from future_agents.sdd.master import MasterOrchestrator, ProgramRun, RepoTarget
from future_agents.sdd.memory import (
    AnswerBook,
    CaseMatch,
    CaseStore,
    ConsolidationReport,
    LessonBook,
    MemoryHub,
    Recalled,
    RetrievalReport,
)
from future_agents.sdd.models import (
    AcceptanceCriterion,
    AnswerRecord,
    Assignment,
    Assumption,
    Budget,
    ClarificationOutcome,
    ClarificationResult,
    Delivery,
    Evidence,
    ExternalRef,
    ForbiddenZone,
    IntakeSource,
    Lesson,
    MeetingRequest,
    MemoryCase,
    Objective,
    PlacementDecision,
    PlacementOption,
    Plan,
    Priority,
    QAReport,
    QAVerdict,
    Question,
    RepoContext,
    RepoMatch,
    Requirement,
    RunState,
    Spec,
    Stage,
    TaskGraph,
    TaskKind,
    TaskStatus,
    TaskUnit,
    WorkResult,
)
from future_agents.sdd.personas import (
    DEFAULT_PERSONA,
    PERSONAS,
    Persona,
    get_persona,
    persona_catalog,
)
from future_agents.sdd.pipeline import DeliveryPipeline, load_state, save_state
from future_agents.sdd.repos.languages import (
    TOOLCHAINS,
    LayoutEntry,
    RepoProfile,
    Toolchain,
    detect_repo,
    language_matrix,
    toolchain_for,
)
from future_agents.sdd.repos.scaffold import RepoScaffolder, ScaffoldAction, ScaffoldPlan
from future_agents.sdd.router import (
    AnthropicEngine,
    CallableEngine,
    EngineCall,
    EngineRouter,
    NullEngine,
)
from future_agents.sdd.runner import TicketWorker, WorkOutcome, default_worker_id
from future_agents.sdd.stages import (
    ArchitectStage,
    DeliveryStage,
    PMStage,
    QAStage,
    TaskPlanner,
    WorkerStage,
    dry_run_backend,
)
from future_agents.sdd.store import (
    AuditLog,
    RunRecord,
    RunStore,
    StoreError,
    WorkItem,
    WorkQueue,
)
from future_agents.sdd.workforce import (
    AgentSpec,
    Dispatcher,
    NoAgentAvailable,
    SkillSpec,
    WorkContext,
    Workforce,
)

__all__ = [
    "AcceptanceCriterion",
    "AgentSpec",
    "AnthropicEngine",
    "ArchitectStage",
    "Assignment",
    "Assumption",
    "AuditLog",
    "Budget",
    "BudgetExceeded",
    "BudgetGuard",
    "CallableEngine",
    "CircuitBreaker",
    "ClarificationOutcome",
    "ClarificationResult",
    "CompositeBackend",
    "ConfigError",
    "Constitution",
    "Conventions",
    "DEFAULT_PERSONA",
    "default_worker_id",
    "Delivery",
    "DeliveryPipeline",
    "DeliveryStage",
    "detect_adapter",
    "detect_repo",
    "DispatchBackend",
    "Dispatcher",
    "dry_run_backend",
    "EngineCall",
    "EngineRouter",
    "Evidence",
    "ExternalRef",
    "ForbiddenZone",
    "get_persona",
    "IntakeSource",
    "IntentClarifier",
    "language_matrix",
    "LayoutEntry",
    "load_state",
    "LoopDetector",
    "MasterOrchestrator",
    "MeetingRequest",
    "AnswerBook",
    "AnswerRecord",
    "CaseMatch",
    "CaseStore",
    "ConsolidationReport",
    "Lesson",
    "LessonBook",
    "MemoryCase",
    "MemoryHub",
    "Recalled",
    "NoAgentAvailable",
    "NullEngine",
    "Objective",
    "objective_from_payload",
    "PatchDecision",
    "Persona",
    "persona_catalog",
    "PERSONAS",
    "PlacementAdvisor",
    "PlacementDecision",
    "PlacementOption",
    "PlacementRule",
    "Plan",
    "PMStage",
    "Priority",
    "ProgramRun",
    "Prohibition",
    "QAReport",
    "QAStage",
    "QAVerdict",
    "Question",
    "RepoContext",
    "RepoIndex",
    "RepoKnowledge",
    "RepoMatch",
    "RepoProfile",
    "RepoScaffolder",
    "RepoTarget",
    "Requirement",
    "RetrievalReport",
    "RunRecord",
    "RunState",
    "RunStore",
    "SandboxViolation",
    "sanitize",
    "SanitizedText",
    "save_state",
    "ScaffoldAction",
    "ScaffoldPlan",
    "Severity",
    "SkillSpec",
    "Spec",
    "SpecKitConfig",
    "Stage",
    "StoreError",
    "TaskGraph",
    "TaskKind",
    "TaskPlanner",
    "TaskStatus",
    "TaskUnit",
    "TicketWorker",
    "Toolchain",
    "toolchain_for",
    "ToolchainBackend",
    "TOOLCHAINS",
    "Violation",
    "WorkContext",
    "WorkerStage",
    "Workforce",
    "WorkItem",
    "WorkOutcome",
    "WorkQueue",
    "WorkResult",
    "WorkspacePolicy",
]
